### ISSUE TITLE
STL export sizes

### ISSUE THREAD

**Issue by Frix-x** [ocgeek/Voron_2.4_Galileo#1]
Hello, I tried to print the Galileo Z gearbox by curiosity and to try it on my machine (we already discussed quickly on Discord a couple weeks ago).

However using the standard "voron" print setting let the parts too small to be able to fit the bearings and pulley inside. I checked the CAD and saw that you exported the parts with the nominal size without accounting for ABS shrinking (unlike it is for all the other genuine Voron parts).
Maybe adding a disclaimer or advice to add 1-2% rescale in the slicer could avoid the problem to other who would also try to print it.

Thank you :)

**Comment by ocgeek** [comment]
Hi,
i disagree with that statement

There is no  need to add any % to the design nor to the slicer at all
It is how the author (Jared) designed them; on my side i only made few tweaks as listed in the page
The hole Z drives is BY DESIGN a THIGH FIT and has to be so. 
That said it fits. If it does not then you are likely over-extruding or not calibrated well

I made two printers with that design and those files and had no issues (again some parts are tight and need to be pushed in like bearings in the foot)

regards

**Comment by Frix-x** [comment]
Hm that's strange as my flow is calibrated using a micrometer at 0.924 for this specific filament roll. With that setting I can push an F695 into the mobius motor plate without any problem with a snag fit.

For the galileo Z parts, I had to go down to flow 0.89 to be able to put the F695 into the accent part. Using my standard flow, I had to use a hammer and a bearing insertion tool that broke the part...

Looking at both CAD, it's not the same size (13mm vs 13.2mm), that's why I'm asking:
![image](https://user-images.githubusercontent.com/10575621/134709162-03faeb8d-d3e7-4f71-893c-932c9ace24f1.png)
![image](https://user-images.githubusercontent.com/10575621/134708953-284fbb5d-c6cf-44be-b762-a469b16b11eb.png)

However, thank you for your answer :)

**Comment by ocgeek** [comment]
I see (and know) your point
On my side i did only a bit of filing of the hole because of the seam that is in the hole itself was taking some real estate.
Again i only did that and had no issues

yes the bearing DO NEED to be PRESSED IN (not hammered in..) and that is by design and i believe intended
Same is for the bearing sitting in the foot. It is pressed in indeed (forget Mobius that's nothing compared to this one for sure...)
While i was skeptical as you are now i realized that Jared designed it this way on purpose as you do not want the bearings to move at all once those are in place

The Z dirve design ain't mine...either...so...
 If you don't like how it is go ahead and make your amendments to the CAD
